#!/usr/bin/env python3
"""
Create or update a GitHub Issue listing all currently broken plugins and themes.

Reads broken-plugins.json and broken-themes.json from the repo root.
If the issue already exists (identified by the "broken-packages" label) it is
updated in place. If nothing is broken the issue is closed automatically.

Usage:
    python3 scripts/report_broken.py

Environment:
    GH_TOKEN            GitHub token (passed through to gh CLI)
    GITHUB_REPOSITORY   e.g. "soulvice/obsidian-nix" (set automatically in Actions)
"""

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT      = Path(__file__).parent.parent
BROKEN_PLUGINS = REPO_ROOT / "broken-plugins.json"
BROKEN_THEMES  = REPO_ROOT / "broken-themes.json"
ISSUE_LABEL    = "broken-packages"
ISSUE_TITLE    = "Broken Obsidian packages"


def fmt_since(iso: str) -> str:
    try:
        dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
        return dt.strftime("%b %d, %Y")
    except Exception:
        return iso or "—"


def build_body(plugins: dict, themes: dict) -> str:
    today = datetime.now(tz=timezone.utc).strftime("%B %d, %Y")
    total = len(plugins) + len(themes)

    lines = [
        "<!-- auto-generated by report_broken.py — do not edit manually -->",
        "",
        f"_Last updated: {today}_",
        "",
        "These packages could not be fetched or hashed during the last update run.",
        "Common causes: deleted repo, no GitHub releases, missing `main.js` / `theme.css`, private repo.",
        "",
    ]

    if plugins:
        lines += [
            f"## Broken Plugins ({len(plugins)})",
            "",
            "| Plugin ID | Repo | Error | Broken since |",
            "|-----------|------|-------|-------------|",
        ]
        for pid, info in sorted(plugins.items()):
            repo  = info.get("repo", "")
            link  = f"[{repo}](https://github.com/{repo})" if repo else "—"
            error = info.get("error", "unknown").replace("|", "\\|")
            since = fmt_since(info.get("since", ""))
            lines.append(f"| `{pid}` | {link} | {error} | {since} |")
        lines.append("")
    else:
        lines += ["## Broken Plugins", "", "_None_ ✓", ""]

    if themes:
        lines += [
            f"## Broken Themes ({len(themes)})",
            "",
            "| Theme ID | Repo | Error | Broken since |",
            "|----------|------|-------|-------------|",
        ]
        for tid, info in sorted(themes.items()):
            repo  = info.get("repo", "")
            link  = f"[{repo}](https://github.com/{repo})" if repo else "—"
            error = info.get("error", "unknown").replace("|", "\\|")
            since = fmt_since(info.get("since", ""))
            lines.append(f"| `{tid}` | {link} | {error} | {since} |")
        lines.append("")
    else:
        lines += ["## Broken Themes", "", "_None_ ✓", ""]

    return "\n".join(lines)


def gh(*args, check=True, capture=False):
    return subprocess.run(
        ["gh", *args],
        capture_output=capture,
        text=True,
        check=check,
    )


def main():
    plugins: dict = json.loads(BROKEN_PLUGINS.read_text()) if BROKEN_PLUGINS.exists() else {}
    themes:  dict = json.loads(BROKEN_THEMES.read_text())  if BROKEN_THEMES.exists()  else {}
    total = len(plugins) + len(themes)

    print(f"Broken: {len(plugins)} plugin(s), {len(themes)} theme(s)")

    # Ensure the label exists (--force is a no-op if it already does)
    gh("label", "create", ISSUE_LABEL,
       "--color", "d93f0b",
       "--description", "Auto-generated broken package report",
       "--force", check=False)

    # Find existing open issue
    result = gh("issue", "list",
                "--label", ISSUE_LABEL,
                "--state", "open",
                "--json", "number",
                "--jq", ".[0].number",
                capture=True, check=False)
    existing = result.stdout.strip()

    if total == 0:
        print("Nothing broken.")
        if existing:
            print(f"Closing issue #{existing} — all packages are healthy.")
            gh("issue", "close", existing,
               "--comment", "All packages are now building successfully. Closing automatically.")
        return

    body  = build_body(plugins, themes)
    title = f"{ISSUE_TITLE} ({total})"

    if existing:
        print(f"Updating issue #{existing} ...")
        gh("issue", "edit", existing, "--title", title, "--body", body)
    else:
        print("Creating issue ...")
        gh("issue", "create", "--title", title, "--label", ISSUE_LABEL, "--body", body)


if __name__ == "__main__":
    main()
