name: "check"
on:
  push:
  pull_request:
jobs:
  fmt:
    name: "nix fmt"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/determinate-nix-action@v3
    - run: nix fmt $(find ./ -regex './[^.]*\.nix') -- --check
  check:
    name: "nix flake check"
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/determinate-nix-action@v3
    - run: nix flake check