name: "nix flake update"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 23 * * *' # runs daily at 23:00

jobs:
  nix-flake-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v28
        with:
          commit-msg: "Update flake.lock"
          pr-title: "Update flake.lock"
          pr-body: |
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

            soulvice will now force-push my branch. This is also an automated action.
          pr-labels: |
            dependencies
            automated


        # This is workaround to force the cachix action to run after the update-flake-lock action.
        # Normally, it does not occur because the PR is created by github-actions[bot]
        # But here, we force push it with my own token, so the action runs after a push "by me".

      - name: Checkout repository as soulvice
        if: ${{ steps.update.outputs.pull-request-number }}
        uses: actions/checkout@v4
        with:
            token: '${{ secrets.GH_PAT }}'

      - name: Checkout CI branch
        run: git checkout update_flake_lock_action
        if: ${{ steps.update.outputs.pull-request-number }}


      - name: Amend commit with human committer; ensure CI will run
        run: git commit --amend --no-edit
        if: ${{ steps.update.outputs.pull-request-number }}
      
      - name: Force push changes to CI branch
        run: git push origin update_flake_lock_action --force
        if: ${{ steps.update.outputs.pull-request-number }}
